### ISSUE TITLE
Invalid Chai property: result

### ISSUE THREAD

**Issue by Lampei** [BigstickCarpet/postman-bdd#19]
I've upgraded from v4.3.0 to v5.0.3 and have run into an issue.

When I call

```
"eval(globals.postmanBDD);",
							"",
							"it('should be successful', () => {",
              "    response.should.have.status(200);",
							"});",
							"",
              "it('should have result as an array', () => {",
              "    response.body.should.have.result",
              "    response.body.result.should.be.an('array');",
							"});",
							"",
              "it('should have total as a number', () => {",
              "    response.body.should.have.total",
              "    response.body.total.should.be.a('number');",
							"});"
```
I get `Invalid Chai property: result` and `Invalid Chai property: total`
The errors occur at `response.body.result` and `response.body.total`  The only thing I changed was to put the new postmanBDD js code in my globals file.

Any ideas what I could be doing wrong?

**Comment by BigstickCarpet** [comment]
Hi @Lampei - Postman BDD v5.0.0 [upgrades to Chai v4.0](https://github.com/BigstickCarpet/postman-bdd/blob/master/CHANGELOG.md#change-log), which includes [some breaking changes](https://github.com/chaijs/chai/releases/tag/4.0.0).  One such change is that Chai now throws an error rather than silently failing when you use properties that don't exist.

In Chai v3.0, the following lines simply fail silently, since the `.result` and `.total` properties don't exist.

```javascript
response.body.should.have.result;
response.body.should.have.total;
```

In Chai v4.0, those lines throw an error instead, to alert you to the syntax errors.  The correct syntax (for both Chai v3 and v4) should be as follows:

```javascript
response.body.should.have.property("result");
response.body.should.have.property("total");
```

**Comment by Lampei** [comment]
Ah, that makes sense.  Thanks for getting back so quickly.  I just retested with your suggestions and all working correctly.  Thanks again.
