### ISSUE TITLE
after, afterEach, before, beforeEach are not defined in Postman

### ISSUE THREAD

**Issue by martinmicunda** [BigstickCarpet/postman-bdd#2]
Hi,

I have returned back to my project after 3 months and I try to run my tests in postman however I am getting `after is not defined` error.

I am loading [postman-bdd.min.js](http://bigstickcarpet.com/postman-bdd/dist/postman-bdd.min.js) as it's specify in doc:

```
// "install" Postman BDD
postman.setGlobalVariable('postmanBDD', responseBody);
```

and here is my test:

```js
// Load Postman BDD
eval(postman.getGlobalVariable('postmanBDD'));

describe('Logout', () => {
    after(() => postman.setEnvironmentVariable("token", ''));

    it('should return successful response with status code 204', () => {
        response.should.have.status(204);
        response.should.be.json;
        response.body.should.be.empty;
    });
});
```

The `describe`, `it` are defined and only `afte, `afterEach`, `before`, `beforeEach` are not defined for some reason. I am using Postman desktop `Version 4.8.1` on Mac OSX.

**Comment by BigstickCarpet** [comment]
Hi.  Thanks for letting me know about this issue.

The Postman native apps for Mac, Windows, and Linux now use the new [Postman Runtime](http://blog.getpostman.com/2016/06/14/introducing-postman-runtime-more-power-better-control/) to execute scripts.  So does the Newman CLI runner. I wrote Postman-BDD back in February, before the Postman Runtime existed.  Back then, each of the different Postman apps used its own seprate runtime, and there were some weird differences and quirks between them, which is why Postman-BDD contains [code to detect and adapt to the different runtimes](https://github.com/BigstickCarpet/postman-bdd/blob/master/lib/runtime.js).

I need to update Postman-BDD to work with the new runtime.  And now that you've pointed out this bug, I know where to start.  Hopefully I can have it fixed within a day or two.  In the meantime, Postman-BDD should still work with the [Postman app for Chrome](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop), since it doesn't use the new runtime.  But this is just a temporary workaround, since [the Chrome app will deprecated soon](http://blog.getpostman.com/2016/08/23/using-the-postman-chrome-app-implications-from-the-recent-google-announcement/).

**Comment by martinmicunda** [comment]
Thanks.. ;)

**Comment by chaddm** [comment]
I have run into the same issue of needed before/after filters.  After investigation, it appears that newman's new engine does not support either `window` or `global`.  I am at a loss if globals are available via keyword.  Because `it` and `describe` are defined in an open scope, they do mount globally.  I attempted to create a patch to fix this; however, I could not successfully build a working copy of the library.  The repository does not have a shrinkwrap or yarn lock and appears that one or more modules cause problems.  If you can still successfully build the distribution files, I'd highly recommend locking the NPM versions.

The fix appears to be to [un-loop the building of the hooks](https://github.com/BigstickCarpet/postman-bdd/blob/master/lib/bdd.js#L7-L13) and call them as implicit global defines if newman is detected.

**Comment by BigstickCarpet** [comment]
This should be fixed now.  I'm still working on adding tests, but give it a try and let me know if you run into any problems.
